name: myChatBot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_TEST: ${{ secrets.OPENAI_API_KEY }}
          envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          directory: apps/backend/src
          file_name: .env
          fail_on_empty: false

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:frontend

      - name: Test
        run: npm run test:frontend:ci

      - name: Build Angular App
        run: npm run build:frontend

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish GitHub Page
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/apps/frontend
          enable_jekyll: true

      - name: Publish API to Render
        if: success()
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
